### ISSUE TITLE
Helper installation Error

### ISSUE THREAD

**Issue by xxbeann** [AppHouseKitchen/AlDente-Battery_Care_and_Monitoring#1532]
Hi guys.
I have some problem in using AlDente.

I can't get precise date. but, when I just update my MacBook OS, and I just tried to update AlDente.

Maybe at that point, AlDente says this error.

![Image](https://github.com/user-attachments/assets/9105ea46-b9d3-459a-bcfe-48c89fe87cac)

I just removed apps and re-install several times.

but it says same error. What should I do?

I use MacBookAir 15 - M3, and mac OS is Sequoia 15.5

plz help...

**Comment by MatthiasKerbl** [comment]
Hi @xxbeann,

Are you able to install the Helper by clicking on the "Install Helper" button?

Best,
Matthias

**Comment by xxbeann** [comment]
No, it doesn't work.
It says 'helper installation fail' and request re-type the password. and it repeats continuously.
How can I solve it?

**Comment by MatthiasKerbl** [comment]
Hi @xxbeann,

Please try the following:

1. Open the AlDente Settings
2. Go to General
3. Click on Remove AlDente
4. Select the Helper Application only
5. Click on Delete Permanently
6. Install the Helper again

If that did not work, please share a debug file the next time this happens so that we can assess this issue better. You can find a guide on [How to generate and share a debug file](https://apphousekitchen.com/how-to-generate-and-share-a-debug-file/) on our blog.

Best,

Matthias

**Comment by xxbeann** [comment]
<img width="473" alt="Image" src="https://github.com/user-attachments/assets/1315f037-640e-4469-815c-b6a5ca4cb5ef" />

I just followed all your steps. but it doesn't work.
I just deleted all files that you noted, and re-install, but it doesn't work....
plz...help....

**Comment by 0x0021** [comment]
+1 macos 26 same failure

**Comment by shitao0713** [comment]
+1 macOS 26.1 相同故障

**Comment by Miagz** [comment]
@MatthiasKerbl The same issue occurred with Macos15.7.2 and cannot be fixed now
<img width="528" height="464" alt="Image" src="https://github.com/user-attachments/assets/971a29c9-12f8-4c3b-9ce3-a189f118c0b4" />

**Comment by selfdem** [comment]
me too.
1.36.2
macbook pro monterey 12.7.6
MacBook Pro (Retina, 15-inch, Mid 2015)

This error do not exist in previous versions.

**Comment by WHaoTian-Hub** [comment]
@MatthiasKerbl I have the same issue. Here is my debugging file

[aldentepro-debug-2026-01-28-10:48:38.pasta.zip](https://github.com/user-attachments/files/24899098/aldentepro-debug-2026-01-28-10.48.38.pasta.zip)

**Comment by will-wallace-fh** [comment]
> Hi [@xxbeann](https://github.com/xxbeann),
> 
> Please try the following:
> 
>     1. Open the AlDente Settings
> 
>     2. Go to General
> 
>     3. Click on Remove AlDente
> 
>     4. Select the Helper Application only
> 
>     5. Click on Delete Permanently
> 
>     6. Install the Helper again
> 


I had the same issue, and these steps fixed it for me. I'm on a MBP 14" M3, MacOS 26.2

**Comment by shitao0713** [comment]
I had the same issue,  try sometime but still cannot be fixed now, please help me

[aldentepro-debug-2026-02-05-21:32:45.zip](https://github.com/user-attachments/files/25099450/aldentepro-debug-2026-02-05-21.32.45.zip)

**Comment by MatthiasKerbl** [comment]
Hi everyone,

We have just released AlDente 1.37, which includes a fix for this issue. To update to AlDente 1.37, open the Dashboard, click on the gear icon in the bottom left corner, and click on Check for Updates.
Please report back if it works for you.

Best,
Matthias

**Comment by wanght18** [comment]
> 大家好，
> 
> 我们刚刚发布了 AlDente 1.37 版本，其中修复了此问题。要更新到 AlDente 1.37，请打开控制面板，点击左下角的齿轮图标，然后点击“检查更新”。 如果问题已解决，请告知我们。
> 
> 此致， 马蒂亚斯

@MatthiasKerbl I have upgraded to version 1.37, but the issue remains unresolved; there seems to be an error during the installation of the auxiliary program

**Comment by MatthiasKerbl** [comment]
> > 大家好，
> > 我们刚刚发布了 AlDente 1.37 版本，其中修复了此问题。要更新到 AlDente 1.37，请打开控制面板，点击左下角的齿轮图标，然后点击“检查更新”。 如果问题已解决，请告知我们。
> > 此致， 马蒂亚斯
> 
> [@MatthiasKerbl](https://github.com/MatthiasKerbl) I have upgraded to version 1.37, but the issue remains unresolved; there seems to be an error during the installation of the auxiliary program

Hi @wanght18,

Sorry to hear that. Could you explain in detail what happened and share screenshots?

Best,
Matthias

**Comment by wanght18** [comment]
> > > 大家好，
> > > 我们刚刚发布了 AlDente 1.37 版本，其中修复了此问题。要更新到 AlDente 1.37，请打开控制面板，点击左下角的齿轮图标，然后点击“检查更新”。 如果问题已解决，请告知我们。
> > > 此致， 马蒂亚斯
> > 
> > 
> > [@MatthiasKerbl](https://github.com/MatthiasKerbl) I have upgraded to version 1.37, but the issue remains unresolved; there seems to be an error during the installation of the auxiliary program
> 
> Hi [@wanght18](https://github.com/wanght18),
> 
> Sorry to hear that. Could you explain in detail what happened and share screenshots?
> 
> Best, Matthias

@MatthiasKerbl  May I ask if there is any solution

<img width="690" height="572" alt="Image" src="https://github.com/user-attachments/assets/d66e0736-9259-4784-a6dd-f8ff429bb1b1" />
<img width="660" height="577" alt="Image" src="https://github.com/user-attachments/assets/2247b03c-2152-4e46-8a1d-653115316886" />

**Comment by wanght18** [comment]
> > > 大家好，
> > > 我们刚刚发布了 AlDente 1.37 版本，其中修复了此问题。要更新到 AlDente 1.37，请打开控制面板，点击左下角的齿轮图标，然后点击“检查更新”。 如果问题已解决，请告知我们。
> > > 此致， 马蒂亚斯
> > 
> > 
> > [@MatthiasKerbl](https://github.com/MatthiasKerbl) I have upgraded to version 1.37, but the issue remains unresolved; there seems to be an error during the installation of the auxiliary program
> 
> Hi [@wanght18](https://github.com/wanght18),
> 
> Sorry to hear that. Could you explain in detail what happened and share screenshots?
> 
> Best, Matthias

@MatthiasKerbl It appears that auxiliary programs could be installed in previous versions, but they cannot be installed in recent versions.
