### ISSUE TITLE
After every reboot I got this message: "AlDente wants to make changes. Enter your password to allow this."

### ISSUE THREAD

**Issue by taylor325** [AppHouseKitchen/AlDente-Battery_Care_and_Monitoring#866]
Hello,
After every reboot I got this message: "AlDente wants to make changes. Enter your password to allow this."
I enter the password but AlDente not run. Launch at Login enabled.
I tried to remove it completely and install in earlier versions but I have a same bug.

M1 MacBook Pro, Ventura 13.1
AlDente Version: 1.20 (Free)
![Screenshot 2023-01-05 at 15 29 13](https://user-images.githubusercontent.com/52882397/210808135-6a924940-4edb-4984-84ee-543316c715a2.png)

**Comment by taylor325** [comment]
Still have this problem. AlDente 1.20 not run on background!
M1 MacBook Pro, Ventura 13.1
AlDente Version: 1.20 (Free)

**Comment by papas68** [comment]
Still have this problem. AlDente pRO 1.20 not run on background
M1 MacBook Pro, (A2338),Ventura 13.1 
AlDente Pro Version: 1.20

**Comment by MatthiasKerbl** [comment]
Hi @taylor325,

Sorry for the inconvenience.
Did you follow our uninstallation guide on our blog here?

Cheers,
Matthias

**Comment by papas68** [comment]
YES and i had the same result













| George ***@***.***  ....... |

 
 

    Στις Πέμπτη 12 Ιανουαρίου 2023 - 03:08:26 μμ EET, ο χρήστης Matthias Kerbl ***@***.***> έγραψε:  
 
 


Hi @taylor325,

Sorry for the inconvenience.
Did you follow our uninstallation guide on our blog here?

Cheers,
Matthias

**Comment by papas68** [comment]
I will do it now and updated














| George ***@***.***  ....... |

 
 

    Στις Πέμπτη 12 Ιανουαρίου 2023 - 05:24:44 μμ EET, ο χρήστης taylor325 ***@***.***> έγραψε:  
 
 



Hi @taylor325,

Sorry for the inconvenience. Did you follow our uninstallation guide on our blog here?

Cheers, Matthias


Yes I uninstalled a few times but still I have this issue :(

**Comment by papas68** [comment]
I followed the instructions you told me but the result is the same
After every reboot I got this message: "AlDente wants to make changes. Enter your password to allow this."
I enter the password but AlDente not run. Launch at Login enabled.
How to uninstall AlDente Pro – AppHouseKitchen


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
How to uninstall AlDente Pro – AppHouseKitchen


 |

 |

 |

















| George ***@***.***  ....... |

 
 

    Στις Πέμπτη 12 Ιανουαρίου 2023 - 05:24:44 μμ EET, ο χρήστης taylor325 ***@***.***> έγραψε:  
 
 



Hi @taylor325,

Sorry for the inconvenience. Did you follow our uninstallation guide on our blog here?

Cheers, Matthias


Yes I uninstalled a few times but still I have this issue :(

**Comment by Attempt3035** [comment]
Hi,
I have just purchased Aldente Pro Perpetual Licence and I am getting the same issue! Is there any eta on when this could be fixed or is there any way I can help track down the reason for it? I too have tried uninstall, reinstall etc. I have included the contents of a debug file. (aldentepro-debug-2023-01-17-08/33/18.pasta)
`uxjw7lZ7TfAC1PDnWjCx8HQauurfKIMuwaRD5vVprfxlsX9Qm+6EMmyQQXDv9NpmMRTCny/5YgPCfCXilJcPt6w/2UdMIDi2NS4VKfVXs9fWFqLLmwzGW2fT2kmErO2Mb66rtlGEY/Yh0Sn6kURWwPX4IvSQS465S9AmKWpXCyxRARTySV92JI8gbVnV1v6rRf19i7W0cAxmUZv9CKVo8Ixc1INttRKdNrNpoUZTvStoWOQRAADM79mC7CqiRf0AoLha2LYqt0oEQgZBBBUVN/jL1mQbNxSxNLNTtxt8P3IzE6om7O7zllX0d+FAGJTNBNEbW8RxIpqZNS5E2IxJZpG341kJAAA9+JoF0msElQ2/RZzSclzGp/8rzuJC+CDXAzaySPsPA0YvYXMSoIa/HuXNmFJyJcTiFgTiyJZRAYj9QH7teInbnrXuAxTrO/Z5BFd7ti+TbtHzun2R4EygWrek4PNXvRNtStFZ5Ga1nEVsCzNza/2y298MvWCwYi6C9yga359qsAHEDqUcab9wucPWqQYAWE0nVu9T0pt4JW+QbuAp/DLskrlLIauys5MlIak5XA8VtZ29kM8o4ZxTXWXv6Y/oC//q5nHwgHpmMgCeoaaULcXv/Wvt3Ux1mEqMoqzqxc4eWh2kx8WRokzxrwPERxP3fJv6ajcAtTY9LuWTFOCa3+dhuV+ppa2YAwd1jvCtK6T9kVNaFYk3qUJdi7SDul5+DJnDEeRSjaa8BBaXbAXgrOFMuBF/QbgVIOnhoE8AVbUJF3AG/+cFymQzMXvUbvfCEKw9NGGZurg+LUkyk5uBUQRrfsuCo27VHIf75lJpqAHMXJddx77tKqkA9sPihWkaDCf3phoCjNRQQtdBemR2c7WyB6Z9ZDgHqZSv8JSUwVl0XNdHMTBXgccLSw5TMF14+l6wizACCVmDca/DjTk36TwwjxSpG/+B8nJaBMb2XFKcq/kWZuKqO/mNFbuj646NOWUFH5jkrYG7bQSkVhjroZa6NHseklZARqvwcIh0oek8m2MwpQwPCGk9WAfiZ57Ir2REEFR/Yv8ZVDyQWXA/T7jpP7/NQklTTPe1SBY1XKcXiRn/luLCZamgQGYU0qaCzynrG/wUy0yOqUkX1xNxav1woXpu7Iyyjdbifx8siHEMzpOd5U8kWfdmTHPTgCsO4nKXfJsbowlI+ensUlioKBOk1x6B1XUMBbzKO95tVctGT3RmmesmG1/lYPzQ981AnoGgbgntmWXWUm74xxmLl/A4yo/XPZ4ZdoK3CUE1o6jq2pJvJ833NkWvZwCY9xVWN4FypMfHo4KEHQZV0EH7fdeTkgbevducOtG+LkzSpdF7MO5RvQ7wdljNMWuJKd/mK3QTQHWZmBu7MZlTGUeGCmn5K275Xu92VOLitKb2wGTex3La4uXxGifGMkfTJvRv0mzRdNm/v8kubzx25Gs322+awzPRplyJ1toHQMxeSHDJMLS0PqBoOxPAc4R00KHk5+fxfozOnBjg6ou0j1qVLrmjThB23zLJHquLsRtwfUSBARkNQ5PJMcfb2RaF0pk42jJek+WFGuhVS+Q164bwBP2lNJBWSKgV587yj4pGqJMDTJF6++yxIOpOh4k+eoxFZcsaZGK4Eoz97K9GA74Dd+eFjkTO3C31rMLC6PToQNcqfrV4qAu1dEUYPTpXiaAsQ3XhwgLftk8kYDO/dqOILWKMJIyJ90OY/aA74tVpbwbYzMqgpPIPBI48rUfjB0lvORLGUjhiHMa4SLwrNVvC//LlTClwH3FMD09GkmgR3ge8cvPTWZACU1z2POjHLMh0ALcJTovEkaDfT/d6UC3I4Q6kzZjQPBE0yN8CCR1ha1qeej4seuOQ7nbET3cxOUuzhcw6NnnGN/715cDgiWJLWGjnBYMg1wNW5GJjlqEK2o2JRzNKRJ0yK/is85YH+wLDPnHY1SyBESjqPUbUG02ehamNyaj8HCuqIn9pb86lK9HhdUZ6gQcRB1g5C/mkta62boGBtnrXAbKUbLmCg/oAIA5ZSa5vtrK1S5XgKIgA1OuaLfLL0aBJza2L4lhEK/OobPFOLPCXYS1f39iYotV2FNCuryJzNproqfAXzs6reK7/KKZ5GbvPziWUgrwaI95wHg7fGiGeCklxWW0HUJaU8vtEad6YAO1yngYHhqyW6LKGdUHwBx79Pkt1yA0iLvOFqj4I8jLyWlOC2l3aaAl/UQXbQirUOEmVIp6p0IAqdmkVMBoKhqBqzUUHFTJBkAAYp1J9jpSPzZ4q85FvbXcfOqeGlH1exgualf1SYb+FyIU7r/lkouiowweYjnqFedJ6stway68Y4kyVcLH00tZYVGEB9vlF4arjKm2srInVKUohZkmiR5hDiRHUvKlR4C6ktVx5pzOx3n22tX9Jt3PrUa8HetOxfyb/nyoc7az8GEA74gfq+VL0eotnD/jMIq5HAX97GWjpan8Fvx3Zva+xz1JV8Elj/4ddDHOcgmR297zRQrlGPdCvEocC4TKzAiM/orghHfFnn2FNhWuNvbMgDiw+nqU8mvNqP+ulSXDhbGx6RhBbWHd7MPpOz/wRJGFeYKlsk2fWm5/n92aeu78fJxZ+3jwgxtMPwywE238Dx2cZe3M0/Jk6ofRk0wMTXK0ZGreFP0o8DwhnayBZ+dq7GHv1IqzhPiRrOZO1NLZr14Bh97LFLKBXz0sCDIV6Kh1tfdALEiAUbrFF+ZXRj51SpJH0Q+8UOUCGQ1+GSKq4tRNp3c9b80T+VMl/IhV/F9fnkz/DMy6wh6gMjQ+6ZgBfw/LXb+pI0tdIKADsi2PSmH4sybuR2Ak5I/aa8/X03lVeN2qjPSAn448I1O0faxXR6GlDiR17juLT6iECGFIhUednVaX+5v1rU7dhr2BTwNZG9KALbYa1NuV7NpYJ5sGiQlaSaVl1u6H4Mywpu46UqMQt9b3/OOEIuTCPQFVGFP86i8rImJQ30l3f3PplNQtGx7KESEawXAAgMn2I/RgbHpN0KL3V4GtIvRY9mHAFjOxDNYT2v56tjoWCdOPbFv+xppb5mD5WXJHvGtpyCnDVM8SaRMtyu/lIMtaImC4KLDcc7UJINT8v5+DB95FJsDtq5eZ37a8kUEoA1H1xM05PMdBoy76tRUkBu3jcirdP4r6HXnPuHqvHklgfYx08Vz90QaUouYGQcSHzPi8mYZI+y4B7DI1cvlmR+6pz3OzbOMZTdoRTZO88I/0eMgKCFBjuioSCggkDuBtR2L2FGKMxZqKda1PGIS9hbqe4b8ovq6SV/h4EoLVcGN5e1Vcnu0NurUqnzBZVDu9UZ7905WEWlCMEwrPVB1CNIjqJ33GxzXosB3cHwIQLtbQq0RErXc7IUSa1ftWPWOPkRBNtyN1rhwCwDpaMdAbtkxby6u1f6KF58bk/UhindOBzOvfemqDXeaRa0SUxC499aS4zc4nizVO7hTu2dySfnSL4RcOynyGEBufK0HxKkZnW0/TmNFJTtLgDAWWq0RfU0XQVx6UNspk93Sj1wx8xH8Ef/lentmIpQl1LiZ8j8h5Dybu0epszHDW1rYKrqGViRsQl+K3kn1B+fjR7KQBIFZKADQdm1ZekAtXrq0H9pt8XmixqkUPRiKOK79sAomcOCbmX75UzhvxvmafkeTh94WtzO4B+mbDNK8jDUbhAOHC4T62YCe11/mBA2UHNxb2zFiBrebbg6T7R8dVtW39t11RK6MLO2LC4fb/VCJNlMOoRgqVgay2UuqesXvoFdk89HxtYPOdbPjmJ7hrc1RnotTuiYd5JFz4BE0xH36K0zFfc+RWSxJ5uHW/BKVo1swNhRW9KQ4frXGhpZRm9Sxa8DlQiP3kNapZVzujoWb7NNrwh5+yCERKwFFvUjokGOTf9jnkjM0AThhOAlvSyqB1axgnp9vWiUmQ+VdoG6ayHXbog8KK++V6rwMSRI3RDtcnmQnYOzd5XYiJIYneUgd4QXor/J/M1aE8CbFPd/7FJJpxuQU6dp+0x39vLsEadV4VM/NKRI1YmSgBmIa/Wx3UQTaKTmDdRr2kNq+CSch1aCORt0sGRqtJJwTIExDH5ARqHtwbkITpBggjmXckyrKSEyG7aqbkoOoPLMLTUimbKSVVeweadOymVk96zsggWTj1z+2fAVaimjFMxIxSj65MMppP/H3+uyML3NxzFWYJFIGwleVI3oPdledY4BoLKMAKXSVmsx/UwdQvY5Q1O+iFdY7nUV5JpraTJfzntSWQ00XjTLJs9t2Y5wMo6dc/nZDC6u8Pb5L1lfTktih1FDUUqvU7jNoCCgHqk4YrPzboVNbPdBU11qZi+LDe1EkL2RWHmXmH02J+Ni6gxXXT/EvyGSEwoNkv0B9q8EiWtlN5tUmciWwxiMjSC+lZ/ImqYXJOqDnQohszBtXYSzAztZB1ToQFuU53wWNCP/hcYkPfbP6z+mXv+KYCOVSXUvzsXhiaIJk3JZWmee7RgTirrWGITV58idEa9Srf0/GuVJrb2HU5JgzbBBkZSF12ikv+bMOogw7ayOgf8O7fBpJJhe25Td4NUHZ2+bH9ZiTBEI2TNErOS1rcIY45SAvhFIpEFa2m0lnj1PJCPj+LhI+GRsVxcKXvIsl3ffFW154YThwgoOkGl7KYXJsLbJbn5NFBZt6a+Q3DJe0/BgQ/k2n9ejDHr/+3DSXT1GQbjXD+pm4KQgkwwZMPkPecoZeRuWooP5mnsbkYI/nuaMBJepdOdNa2KNCOn0FHbZKpSPtkqoNfBnN97cg99DzTlUW9xPc22yr5N2+yKdh56sx9sWMiC0KpS/rrwGBHEqV5S6t5ffZspHQNx4ja6TMtd6NooGPYBIxRK8R3W6UZ62E4MwIWVg20PGHdnEV1ys3JM48fiksQaOwM9ve6pAbQexIii3lKJYEnJOtWugYSfky5xSGiJ5uK2S4BGtfm5OgfRMVuUP6VrDny9ErQSrVzY+wbT5xuhMLA3llTE0nGIXqd57+86lWviWGBHNZrhwhfIex50IeA22b/S9ArdnqrUQ0z8y9rJdJTGAPvdTJGgYQxB1p4x4L9EJZYv1qe8FQKU8YWDwIVo+XpXkaxf/8Eigr14MQr9RFsnXgTvjuM+wBh9OKjuQsm/aoXsLlD8lqXnoZoxLF7TP8IIxAm7YaP/TJkR9ay2nSaX4X7MizTJxy0BcIImcJ9IFANSBEQmrruklYYsqXZQAcd9rrD5hewkZPto9NyfG+um3CTXTJr1AqAVfeDMMjkSqopnsxmdUDuEkcHtaGppjT+SlDlQHGOmRDPiWDNNp3If4MDlQyPZc585OErby6/2qeHTXGmqAjfGqXfuvrleSeJujElnSBWCrTMaUQutrlrYdkt2hj6UKFgiIB+9sUfqED0ZfBd2h90nhT0Hxyo/Z4N7ipHEmdY+41b0eIei/NjI9N84ghnZxtP1b5NKR1CvzDBWBu15ewZYI7yJqtIoLuIhlx436ewO9TSVoUMWkOab40+zXYfDnQwGlk+Kvr9P1dVL9NRDKzU3C2Riw1UlBlFiGRiucWHycj2sLbZ5aQF/8iOb9e58Q+5x5FuBaG40bredEl+4kVEOB5tG2G0lKP0nQhL850pOEYkIFcrDXOk39tf0vEsz4GLxMZf1NI1z4AgcEi0FtarZA1cfnDjPo2onSYpzkVl9M3aF2W57dXzIOWDizS+7Fi7M/wmQ1nNG4IgsYA2iLjBiWT0cDFDb4Kt6fWO1wfCmRMOW67+x43kPznHedUCaRHehqtu3Y4RCMsKC4MIn2ceiAhvxD39ljWt386ekA8haNFnnFp5p1OkDif9Zqvt0bm5FyYfFfGHwKk/2LruiR9RwHmpX5vZ5XOGwfPJOsOZbJHSBuyQNtgwKFMEq6AwWaqsWyCPqvPjOXAQZgSESpPQtAYqFQhK/Ol0BbfUXnSI4f5wpf0J+1pR9O8mSbJT4PCiK6lUs8DVbNkNShIzzVqT8FyYwyEco8ZAvuv+NUPey+c6OxY84/vugcRchQ+ZtTnjEm0KYSTwzrz95gpdrHASs1pJ2VoX6CV5SMow7L6j+stXwzTm2Sca7pXcB2Z/ES5UcVlamNsKY/cQJjMS+AxTao2tgL85DT4d4OJIegqEqmMV5TgA9JF2IPJefdPHn+4c5YkHXc44l8TeUmowvgzjykyIr6OXQxMad02lJL5WLFOjwbngM7OrS2zRmyXlw9sPUq4YBaaZInYtZN2pqok1ZRfFQnc+ZNqxu3ntVyWuE2VI274n3s0QocWqDzh35Gzm491t5TRHdoGF09huqOf1FIN1vE7wcat684stLn7icYgkRNIKJQIkfGTcg/GO9a6qJTSNyfao0dFKzHhmWnr7YNP1L4FCDDazYvyJj9b45+jElE8Y1bUr+XqORWVBe01Iw6ahUpExJyBJ9V7tMJPCSfbtYO134WGg/zGB6x3PcH/3A037krMpceSgLW3FqpX0NccEksP1eVuM/7N0lqdcWnC5qo+xYA2OrWQ/cNMUaevzTISMH6xa6l0GQgC72KD3tmClHCNqSKxSfMg92y2jpzzVYwTonomqimov90iGSFIuLxOs+W+XhUe9Qf47TQuSaND05a5vRJ3EVUordVbW3830HERPWQnML4Kx3rO1TtOCCSNxieQuZeAFTurer3d8UF4i6TBIGLg4KPOnNCfHi0STXTl84s8Z5SxBl/zb+R0/WEJZCfw3QaRCMFlCSQhcKGdPvGB90J8VYvzd8bld2oQBehmisFkQPjfdR9AS6B+3pd9RKcoFjx8Gz9U/tcMl6FldLhtXdoJvt30Jek/aIitAJ00veXgOvG3n1MWTjyt6UtlbtS03Ofbk0mjGdYNuvyGIw39BoabOZIdxgk3mTbrnK5LPJW7ygTw0sc/x69qOZ0YhPlKiGtrEI8aWCU57XcEByMGDC/s3SAq20WD68aTgCRBzjS3O0aE/wqaVxOKBM6JbEdWXe9MSS0HYleh9HaS8mGTZo8Z3F7g70uJL9pg4ybzU4+a6RrA//qkWs0njeFTdLRUOof23/vlVQbaw4IRCAt+IV8o7txxpRPII2ypc98bDnrjVgJtcGH2mplt6pKJ7fn7452pHzSdUUhpGnRjtr/N3JwYzGUMgFvJarVR7GdH9xpiqaHShprDKOXa2A6KJ9t0eMKXekze1Mvi6705WfaDtXUUUVkmANSZoC0gcCyBDQQpM2vFwc935/hrdHRRelGoiwq0j+H84KOBhjbfmow4KEYvH0eG45//8mq51gaP0GKa2tdG9xm9w38a1WLWC3iFWl39pV1qRuVO75kM14kcvkpH2dtS0kS4mRE3ynSuBAYWoJYs5DvBv3m1EGK7dAhv0K/WOZAm3Aik5RsmqMACJ7Pv5EFUPLBA3mbKlHCeHS+S1xeJLh04cLcOzr6fs0ZOb1AB8cUrF+nZL9oLGW9gyBk3Jm14n9C6w5wn6lGIA8JzqtQWxsDOeLnCwthoA6H6JX2+tQwPd9/+bgoTtLvnk2Pq6lnz671DAC8SI004/f32ux4lgxCEiwKcRQDt96nCGPLgWhHeYCrdBevJdrXkGbGp5i1jzEWpO8yifpbw0GUufOear3IqBUuWJCgQ2V/EWQMPJbZ/+L/Sz/rgkVKMw0hsxAMojM+grh/8k1Iw5OK7YYgJzoZhDKzuVUeYvVYpzPPAdrTk+4bH5WKnlYmTljEibMpCZ4yKJCfBsQP2eIcagvQT+49NZCvj43BZmVn4luvewxOSjkLKhFJamjCyN67TzPOBJhylRUZ/gDjyrGpeu8zWqIuQoqJVSvGPh+5iCxSOf86zRZ5n/Ue+tSYwWBRmCVrzGcM9WYNyu6yUNSDaJRncMIUH6q3UI33m+odxm+/2Lpe4MyDWXKk8uj4w5vWEBNzSezDjvOixm2eGU4xU0JN519j0wvwLTJ2LZ4Ie3fgRYhpb1mG376z2BUfsUInarcLgZJeZI4AXtCHF5iDqpaZnajL0qlROSHyezb1aav2wzyyspRSa07Mvbxrz6ZmqEuy2SdINqHg2yNXRUsd5dJ8h7ZnA2POyuasrNN09+SGXSorFMpmgxm5GT2H6FPc9BdZG/HWIGHkzjNAQZ42XXyjVJxvaqslFQ4s17vdIhM+ooOG2kudq9AFm3rDD/qMXhO5OjvHdO24OeXermpqQfKGMeS3DtrXSX6I57EqhgCnhX+iNxsHM9Ssahz6GgO7f0N4iTXXIWAhEMeH1lVrzFG4RWolIhxm4+v3HgptIOBNNQuGghjQMo7fPrtWkO+1I42g4IgXkq7hkjIK2OOviAFFADtxwRcxQXS51sFg1i/G96jOG7zFS8ZvJaPuRp4VTLzpOsDO/OLAUpcquc0QSxfwBdXWQHGyapTj7eUpNoINK/VvdmyWPEkKgbEyD4v4u3s4GLhcxobMP3vjatHxVJNusnGS/1JnvEimAC6bNMFIrhMFOjT9/H/raKbMfp7OXVHp0WmAS8g/K7J9oxzSjm+Q4h2vnZCJ8bDkZLUUiVWievHc4TlYulc60R77K6DrXZLd4py5IjWqpRG0uZfEfudxqz0RiGiq8KtJPgGdAoWWYjcEW3F9ESlTEMVPt/j3GoQLQNgrrf1HqK6Td7E0Xbh3PKLLp2TWvuydybf3VOuFOhiY8T+Il0W+4fgoKvRU+1K9hati0BdoNc4Ob15/9tgpfHIQpb63U5u2SJMIyn2Fx+B8m/tzOoFXSJ+eHuXVFh3gKxvyq7uxLqQ5ZM3sjnCPwqjqvcvj0FpPkKZAy7Du75mhmI7wPgUw7wTS1AqXFvgYwHDclYC/G6a/ANrrKSYugS8x2/TUYkGV3yBDuv5gRvQsNCl6AJQlyDVOugdFCMbtzvEyWYMuZDwxE9ivyw6Qua5ct6UXz7WpLDYiJpAPZ6BhArTGO9SpFJTiEMEZvl0dGN3ioelvZ2xHGw5S+PpYWKCzrlCdJGGYpLjcmDQnzeX8wO/WcjF9zj4OBzCoZPl7hQEUH2vAGpApzaJLgyqho5jaawJ/VGQYgvmSUxGoPOVzq1r6gTyzDvZQ+5pNQ9sqIao06GldUQw2PFcwJsF42YXZASHAPSLdPVx7bTH9Cv1LuFIjmZnHz/AN08Kz4fUOyfqUM7SoaUi8I8LyzvtmXrGzkQBvsPyJkWtff8v/TgEUjnJfZVakUmLTG/EP95Hu5m5LmS/8B/gFXfxL9EOY+Gu5KND39JqZ2bi8EMxPY52bqxMZ/5Y4M6CqzbKlWiiomj955Ol1w1Hrqb+LHIQxlCAkBnIjnoNDVVnrfHCRLHjClyffql1hqioxdu7Cpq+m8UI7NOIKAUt3DdlgGIyCw48FvftELso2859jQuLS+rVtLW1clHjOcbCZ7qLfaxVQOjGe2RpaxiFUxI6WQellpI/F7eSlKM0vBn4o0lmDo2AV4hdJHafdR0FhHkg+f647VwhdlKfFQF4JkdfO6RYy+Qr/rIfhtpSARd6Y/JwDSQz5IQBhCIKzOLOS2L5E4udIfZr4d0En/aXKpwX1KYph1b2KcF5xBN9ziu3FTu8wBYRlzUWoOA8/ZZvMN7HFAMxtfja/06YX+U0JmIS52XQCHbcHAFzJcEELkN9ItJjSdUiw9MNGHjwuOP4shUv4hqBBMp+tBfrKaxt6WnTD13bnGqflGJe3cE21n3ZEPsSUnZVcC4F+p0xxBAYRv0I3BUDrdrDXKEzqIFCaoQMDDCiXvCdnekHYmjOSu1kh8q1DaDLertkjHfRaiQmy3OnpqL+hu3yZ4lrAHhptqDlFsdRKTnyNRVhhA1j62j5Ezq7n/CpxETFTCT+2uAQhEg++s/7+U5Hal+IjRiN8SstbLIdVmgLj6Cga1JaFe6/GawvfMUGa9wAjZSmkActVvGl9E9dGqU/i33mV2uBRh+HGbFilQyQul4QtzuGe7UX9hu3m4Jsyv2aG7pofmBQ6ZedUfAn1ZKTUc7JSQi8Utf/Ucruo7jCT8D2qERpsdDN0zlCrL+a4rITixZ5DnXHb/6vkoG3onvMJErup5WK+c38CxOidM0402GKseuVgsqFtL61+7uDUnMwIQLGJuTz4pOVgE26rwXb8Nt9DGt8ScQ+MzybmrNk8wqvHdflUlhMNZWDzAu0YpCWPQoNp6QdEjM22oBBaVp3sNBwf3og9/oF2XN4nh20a9K4zPtOaDIJwuZdnyU0MaaeENXrwfh8PRID6IggWskGheJ/QDLvYdq9IYyvPjNEgk66ClNgPzuk/2xT0Y6bFzC5vx6QUyRHHhieCWW+B6fXfghHZkXFQ8Wq6zmA0MSUv/Cm1X5GJaz1a/fgirBT0qZWN9/PU/cAcAOv8Mas8hryhsuvqSATkmERi2NYnQatg5q4B+bX7HrLCpvFRVmR2ZL/zTwwVzyOuq+DxG6wZAJ0L7RL184uno+nOGKQVIr+qhevWtZezDOEdkYyikGPWO+ucAFG3UhP0bycIok+IB5940jRj8k1P3uVQjNaOxZGCHy2K4VOL9yJubR2hccQMjXmQ+sBeFK/+HgPhsXcD4C2TyMtrgK1nb0oMfK34yQWTM5dUu8IT53b7MIgKD7bKUjMYUuAxjsjH1OW2LmA102oG54hZ7NOSgbeGxry6P13V7+BV7ycl04IY/T9Wc8eLPX/KCeI/uMRwOYbQS9oBtQIP2dFXEeyZhtfj0vuSUPTMxESTxcApHeA7aOrASD2Sqp2rJK+qO9nBGwLi5LN4cUwjSaTJMpq1bmeyCUn3Bwmz+FrT81ni6CLyAhV0yg9nEwzspDFmn57caU0iyqExIeahS38mHzd1iGE0EtkMncrHkQrZNX+xzvZMIgjKzRqIPR7eWsIIBwE+ro6k6+uqt9hNOJiQCJjd3uTtlR7eiC5wUO89vjqhL0zjpUT+wAw+Cx5sIrHJIBp8OA5yVoY7jpdfvZSdgvfLnVoOqngP+7McGFILk9GtsuSGTEYiH1KRggdvDNWAXcFQyxLgVBIHOVH/81WUU92rXgfC0WOC6pSIbJcyNd4KKK+DbiR3XNlHdshcalwm9NQ7NwJyjRK9fvgTDtKgH5VB2BowZFcL7yOIEgI7roK+/G+kK18WodNz4507ktPDPGhUMGipmG84lyzFFDsH2S8zp12uJ41vMeU0DepZWN8j56PM/uiFHP5kI9JDRSkWYz1tfju4SFEsMeG0mPtIF1KnubzSIkb+MciNLm+8Arxr1ExVC6wqaTeKQGhRkfD1Gx1zBMJs1huDm2AvN69945AvFaf+PvJ1/VGzu9y0QgRZgo2mFwMqnFkzxb/6Maxcn3um7fPOO0Pf2Rg9ZGZj5gdHLIS4PCA7QMyIgN+STJblrCF9NfkRYoUvR7nKcy+IaxKjaFy6nX0pYnM3YeK27zn23VbGDgBGVEgPs1MlYdeI7DfuNZZIkoJfEHHtSUK6quauVp1PmepSCGv+OEHd+Euoiq2j8waF0/KaMjODdGQxqzbdNZIRkgSNf4w20i+mAKnNf/yEo9AmOOXWaBr46i2T5JmbDRTLurLsr5A+cCoJIAkXASICWKlhoGpGBrEInLVqSlhSrZs5Sbohiet1XfBLmeUQV3PUxvy7S/liL0AT8+76nByTMZnsdUmuFxd39UpFiybdzEmN7ZlluMzFviRWly04tP9FsYmRSStln5ViijBFbcg9DbZ0zh2HID5MmXEtqFdefuSXX6I3HMaRKOH78hA5cjmws+rZtXtC0gU5AJC6SJ4vFoPr8pRYNvbCOG4oWovJThmx5xADXtwJmVZha1rKPff29UG9B6Tg4tXA7Tp8CYPzrEvHO74e3S+U9iThGVTasBGh3H+yCqYFnwtXzJsARCLYxqpZIyS7OyyNRahPG3r6W01BQ655d/gt8Lc47ZFPyH5ZvV/swAjZ1VtxYDMukOV5LlfLfBVD0/n2b+BFhCUjdj+HE61eJhpuxP98yUQAEvsCoL9nTaSxuV+mQHarjjfdB1nDkvLUqjYQSINXkaUBDbXnqHTF37MOeiY8g+M3l3DKJFmcEuZn+bWTlPJHbT+7Y2LIVfBZ3Lg33NyBVzALMPV+/hwj0t/wpcNC1CC55YiYkCp+Pvxyf2AynFJ+D4UoUooCzkaO3mDAyApTojhX8O99Ihop2ayxJXwfaKK4Mp6KIny+ymjfyHT2cgU/6W+l/7+VhaPV8ofR6tY08mLvtprTItgY9kq8fObge4ZC22VqhVO7e5OYisP4VUnVGGm3jjliHF9SeM2E64Kpd67pzGR7ZcPADJKfFZsIvFu5qdZJqv63zNX89pHhccUNz85G9EqPB/SR6Nwoty5DvCzSphrudVW1gzzlCondV746iIUxbG1/pcFmU4DyGj75bAva5AX1yzwRG+CKQGWUddr6pnzmbgwSqp4W/29uS9iOPkLg+Vd6giimwOQ2zz5upC1RbfKAFSFT7RxjxhJF3/z1Z88+5iHMwdxiynElyD1eySBbjT+3V7J+LpNftcq5TPjbLQJofaxuest4guXLZ8aPjRVm65J88wUHCMUxX7rnxNB9Z0aWmkafuQFBiknf7gsmiTcl22q/1CtKd1q3/w10rG7ssI3JzJGmiLglc4Gz1H54NX6egD+SXXgh3c9fDyQ4Llli73/bnC/cwQEEh8k29NiEvnkCHvCT7evjc/aJK1dMBXGLCWp/pnjZXa+pOfnQ7PLn+WUH3knSmrKtkj4r9ksQDqAClVpEUv8cC1njPzZ/2IPXEVRwxVdsEeWqvbsfqYfi6ASRypVk+dG234jjwGZeHhr2at4OPO7TQaTGZmLIy2ZMAI5CiSRfBFGT/UsotXzbMQIHqWJzohsvK5zKHfKI+7pHcyfeky0U9WODtCMZEYcmIlJIJrvVygacWVa92L1s6rOm0lwqZJ8yNF4DW9pJUnCsH15rEx5qTdDPRF0lnSJvCdiGZpZyYs3z+zqrccSJAH3yFrQ9UVclMRGPTJf6qg6Y+FATVcMfkvoSwoxIVrImmgwTZs1HJy6yCC5BC67h4bqkJI2x3Zm309uh6KjmLO26ghxix3gUVoOr+3yhr3kon1nHySxqAMaizAlDUZAzRdM5QX+OXbc/Jo7yHNSRdHtyqTGSJPk9gaQ/mfPZZXV0IoWwlqaJvSDbI9jSSRTigQLtBHDdl9jmrUddkeirkytuV2bSatkAdrh6W1TwrV+W7xr7bA3l2nGIVM1pn0dgIguAhh5AolUjm6ghTcvgQbWhTPGVb06KWTrROM6OERHpP87vUhlJLz2WhM+LuwZtcS5lQjQgehp3kk4Seb0Ekdi4X8A81wkautOxbL5BtVz2B2CVo4sOfgnJAVDvMnYoCfswevTPKrtU4RtZeEJ
`

**Comment by mikenadeau** [comment]
I have the a similar issue with AlDente Pro 1.20 on Ventura 13.1 on a Macbook Air M1 2020.

I say similar issue because it asks for the password each time I reboot, BUT, once entered, it launches and runs fine.

* Running in the background is allowed for AlDente;
* AlDente is in the login items list.

What is it doing exactly when starting up that requires admin/write privileges?

**Comment by jrittvo** [comment]
Same issue here.  Need to enter my pw after every reboot, and then start the app up from the Applications folder anyway. MB Pro M1, 13.2.  I think this started happening after upgrading to Ventura.

**Comment by 23727** [comment]
Same issue as well. Ventura 13.2 and Al Dente 1.20

**Comment by confluencepoint** [comment]
Same issue as well. Ventura 13.2.1 (22D68) Al Dente 1.20

**Comment by netique** [comment]
Same for me. I tried to reinstall the helper service with the button in the settings. That didn't help, so I removed the app completely from the Mac. That didn't help either.

**Comment by MatthiasKerbl** [comment]
Hi everyone,

Thanks for reporting this bug.
We have investigated it thoroughly and will release a fix with the next update.

Cheers,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi everyone,

We have just released AlDente 1.21.1 which includes a fix for the issue you mentioned.
Please try it out and let me know if it works for all of you.

Cheers,
Matthias

**Comment by papas68** [comment]
After 1.21.1 update asks for reinstall helper on every reboot
M1 MacBook Pro, Ventura 13.2.1
AlDente Pro Version: 1.21.1 













| George ***@***.***  ....... |

 
 

    Στις Κυριακή 12 Μαρτίου 2023 - 02:27:38 μμ EET, ο χρήστης Matthias Kerbl ***@***.***> έγραψε:  
 
 


Hi everyone,

We have just released AlDente 1.21.1 which includes a fix for the issue you mentioned.
Please try it out and let me know if it works for all of you.

Cheers,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi everyone,

This issue seems to be caused by two potential reasons:

1. For some reason the helper application did not get updated and the new version of AlDente does not work with the old helper application.
2. More than one AlDente application file or installation on the system exists.

To fix these potential causes of this issue, please follow these steps:

- Open AlDente and go to Settings/General/Remove in the Helper Application section and remove the helper.
- Open the Finder and go to the Applications folder and delete the AlDente application file.
- If you have more AlDente application files anywhere else on your system, delete all of them as well.
- Go to finder and navigate to: /Library/PrivilegedHelperTools/ and delete the file: com.apphousekitchen.aldente-pro.helper if it is still there.
- Navigate to Library/LaunchDaemons/ next, and remove: com.apphousekitchen.aldente-pro.helper.plist if it is still there.
- Restart the MacBook
- Download and install the newest version of AlDente from here: https://github.com/davidwernhart/AlDente-Charge-Limiter/releases/download/1.21.1/AlDente.dmg
- Restart the MacBook to check if the bug is still happening.

Cheers,
Matthias

**Comment by taylor325** [comment]
Ok. I followed uninstallation guide [here](https://apphousekitchen.com/how-to-uninstall-aldente-pro/) and redownloaded AlDente from [here.](https://github.com/davidwernhart/AlDente-Charge-Limiter/releases/tag/1.21.1)
After 2 times reboot finally AlDente working normally.
I don't know if this solves the problem permanently, I need more testing. 😎

**Comment by taylor325** [comment]
Hello guys!
I have a temporaly solution: 
You need uninstall guide from [here](https://apphousekitchen.com/how-to-uninstall-aldente-pro/)
After complete uninstall you need reinstall AlDente Free or Pro.
After reinstall you need reboot and please go to mac system settings, general, login items.
You need remove AlDente from Login items and please close AlDente.
![Screenshot 2023-03-13 at 19 20 29](https://user-images.githubusercontent.com/52882397/224795454-d639f75c-de11-423b-9c58-d414e5b3edbe.png)
Open AlDente and you will see this notification:
![Screenshot 2023-03-13 at 19 23 06](https://user-images.githubusercontent.com/52882397/224795502-8ffa6cb9-a84b-416e-ba90-66351e3e0e9d.png)
Just reboot again and enjoy AlDente! 😎

**Comment by MatthiasKerbl** [comment]
Hi everyone,

We have just released AlDente 1.21.4 which includes a fix for this issue.
To get AlDente 1.21.4 you just need to update within the app under Settings/General/Check for Updates.

Please report back if it works for you.

Cheers,
Matthias

**Comment by danieleleoni** [comment]
I already have AlDente 1.21.4 because I purchased the application few days ago, but I have this problem
Just to confirm that uninstall completely solved the issue

**Comment by Zonaldo7** [comment]
I have a pro license and upgrade Aldente to the latest version and still got the problem

**Comment by MatthiasKerbl** [comment]
> I have a pro license and upgrade Aldente to the latest version and still got the problem

Hi @Zonaldo7,

Do you have "Allow in the Background" enabled for AlDente in macOS settings?
<img width="670" alt="login items" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/33470003/6b977a1d-c8bc-4866-ab54-6e585bfe464a">


Best,
Matthias

**Comment by MatthiasKerbl** [comment]
> I have the same problem. Just tested now to be sure, the issue is always reproducible.
> 
> * Macbook Pro M1 Max
> * MacOS Ventura 13.6
> * AlDente Pro 1.22.2 installed via SetApp
> 
> AlDente Pro is set to launch at login and is allowed to run in background, still every time I restart my computer I get the popup to install the helper.
> 
> <img alt="image" width="324" src="https://user-images.githubusercontent.com/3300747/272997781-fc7f5972-a8f9-4f52-93ec-ea24fa7972c4.png">
> I'm not sure what would happen if I marked "Don't ask again". Since it requires the password to install the helper, I guess it just wouldn't install it anymore and probably wouldn't work properly.

Hi @esimioni,

Thanks for letting us know.

Did you try the following steps?

- Please go to Finder and navigate to /Library/PrivilegedHelperTools/ 
- and delete the file: com.apphousekitchen.aldente-pro.helper  
- Then, please navigate to Library/LaunchDaemons/ and remove: com.apphousekitchen.aldente-pro.helper.plist 
- Also remove your AlDente application and reboot your MacBook.
- Then, install it as if it was freshly downloaded.

Let me know if that works.

Best,
Matthias

**Comment by esimioni** [comment]
@MatthiasKerbl, it worked.
When I saw that the bug was solved, I was expecting that a new version would fix this automatically.

**Comment by trss** [comment]
> Do you have "Allow in the Background" enabled for AlDente in macOS settings?

Allowing in the background solved it for me. But I don't see the connection between the two and would like to if it's not a bother.

**Comment by huyz** [comment]
> Do you have "Allow in the Background" enabled for AlDente in macOS settings?

I believe this must be done for the `David Wernhart` entry as well. There are two entries total.

**Comment by trss** [comment]
> > Do you have "Allow in the Background" enabled for AlDente in macOS settings?
> 
> I believe this must be done for the `David Wernhart` entry as well. There are two entries total.

I see only one entry:
<img width="827" alt="image" src="https://github.com/user-attachments/assets/e51adcad-cabf-46d7-b64d-cacc34d5a0e4">

**Comment by MatthiasKerbl** [comment]
Hi everyone,

We have just released AlDente 1.37, which includes a fix for this issue. To update to AlDente 1.37, open the Dashboard, click on the gear icon in the bottom left corner, and click on Check for Updates.
Please report back if it works for you.

Best,
Matthias

**Comment by trss** [comment]
This already worked when allowed in the background. Still doesn't work when not allowed in background.

If this is expected, could you respond to https://github.com/AppHouseKitchen/AlDente-Battery_Care_and_Monitoring/issues/866#issuecomment-1399606384 and https://github.com/AppHouseKitchen/AlDente-Battery_Care_and_Monitoring/issues/866#issuecomment-2365167702 if you don't mind? Or can we assume you feel it's too involved to be worth discussing?

It's just a matter of curiosity because anyway it's going to be left running all the time so knowing the reason doesn't make much of a difference practically speaking.

Thank you.

**Comment by samdsgn-studio** [comment]
Solution market on this reddit thread:
https://www.reddit.com/r/macapps/s/hCkApt3SuR
